spring:
  jpa:
    show-sql: true
    # 格式化输出sql
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:oracle:thin:@//192.168.90.230:1521/orcl
          username: fams218_1111
          password: fams218_1111
          driver-class-name: oracle.jdbc.driver.OracleDriver # 3.2.0开始支持SPI可省略此配置
          # slave_1:
          # url: jdbc:mysql://101.35.80.154:3306/dynamic?useSSL=false
          # username: root
          #password: 1234
          #driver-class-name: com.mysql.cj.jdbc.Driver
        #        slave_2:
        #          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
        #          username: ENC(xxxxx)
        #          password: ENC(xxxxx)
        #          driver-class-name: com.mysql.cj.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2

dataloader:
  main:
    runscript: true #是否一启动直接执行sql脚本
    url: jdbc:oracle:thin:@//192.168.90.230:1521/orcl
    drive: oracle.jdbc.driver.OracleDriver
    username: fams218_1111
    password: fams218_1111
    #filepath: D:\日常工作\fudian\06_脚本文件\处理脚本\升级脚本 # 脚本本地路径
    filepath: D:\日常工作\fudian\06_脚本文件\处理脚本\升级脚本\2.1.1版本升级到2.1.2.1版本增量脚本\1.升级版本脚本\1.基础脚本（2.1.1版本升级到2.1.2.1版本脚本）
    #filepath: D:\日常工作\fudian\06_脚本文件\测试 # 脚本本地路径
    # 以下配置是生成数据库表结构清单使用  默认只需要生成一次就好
    generate:
      imgentabledoc: false #是否一启动就生成数据库表结构
      fileoutputdir: E:\\
      enginefiletype: HTML  # value: HTML MD WORD
      filename: 富滇银行资管系统表结构

server:
  port: 16080

middle:   # middle server 专项配置参数
  server:
    websocket:
      endpoint: /demo-zx-websocket-midserver  # Websocket通道地址
      test-topic-scheduled-fixed-delay: 1000  # 测试专用，定时广播topic的时间间隔，单位：毫秒
      websocket-message-broker-stats-period: 1  # 定时打印SpringBoot Websocket Session统计数值，时间间隔，单位：秒


#密码，因为接口不需要权限，所以加了个密码做校验
mySocket:
  myPwd: jae_123